
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Misbah'
tagline:          'My personal portfolio site'
description:      'Software Developer '
url:              http://msbh11.github.io
baseurl:          /msbh11.github.io/

author:
  name:           'Md. Misbah Uddin'
  url:            https://bd.linkedin.com/in/md-misbah

paginate:         5

# Custom vars
version:          2.1.0

# Google Analytics
google_analytics: UA-145483609-1

github:
  repo:           https://github.com/poole/hyde
  
plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
